app: wayex
backend:
  kind: datastore
  conf:
    kind: credsFile
    project: casa-de-kylie
    value: ~/.gcp/kylie/wayex-svc-acct.json
defaults:
  app: wayex
  project: casa-de-kylie
  context: casa-de-kylie
  docker:
    #    creds: docker-credential-gcr
    #    context: .
    #    file: ./Dockerfile
    repo: gcr.io/casa-de-kylie
  helm:
    #    chartDir: ./deploy/{{.App}}
    #    destDir: ./deploy
    #    save: true
    name: test
    args:
      # version: {{.Version}}
      # name: {{.App}}
      set:
        - image.tag={{.Version}}
      name: wayex
      version: 0.7.1
  tiller:
#    namespace: kube-system
#    labels:
#      - app=helm
#      - name=tiller
deployments:
  stage:
    docker: {}
    helm:
      args:
        set:
          - image.tag={{.Version}}
        name: wayex
        version: 0.7.1
    tiller: {}
  prod:
    project: casa-de-kylie-prd
    context: casa-de-kylie-prd
    docker:
      repo: gcr.io/casa-de-kylie-prd
    helm:
      name: prd