app: onboarding
backend:
  kind: datastore
  conf:
    kind: credsFile
    project: unity-ie-sre-isolated-test
    value: ~/.gcp/isolated/test.json
defaults:
  app: onboarding
  project: unity-ie-sre-isolated-test
  docker:
    repo: gcr.io/unity-ie-sre-isolated-test
  helm:
    name: test
    chartDir: ./deploy/onboarding
    set:
      - image.tag=${VERSION}
  tiller:
    context: sre-test
deployments:
  stage:
    docker: {}
    helm:
      set:
      - image.tag=${VERSION}
    tiller:
      endpoint: https://api.k8s
